# name: Deploy Website

# on:
#   push:
#     branches:
#       - main  # Change this to your main branch

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Set up PHP
#         uses: shivammathur/setup-php@v2
#         with:
#           php-version: '7.4'  # Choose your desired PHP version

#       - name: Install Dependencies
#         run: composer install  # If you're using Composer

#       - name: Build Website
#         run: |
#           # If you need to build your site, add commands here
#           # Example for PHP:
#           php -S localhost:8000 -t ./  # Replace with your build commands

#       - name: Deploy to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           personal_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./  # Publish the root directory